# CircleCI jobs are only enabled to on Pull Requests and commits to master branch.
# "Only build pull requests" enabled in Project's Advanced Settings.
version: 2.1
jobs:
  build_test:
    docker:
      - image: cimg/python:3.6
    resource_class: small
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install Environment Dependencies
          command: |  # install env dependencies
            set -e
            pip install --upgrade pip
            pip install -r docs/dev_requirements.txt
      - run:
          name: Black Formatting Check  # Only validation, without re-formatting
          command: |
            black --check -t py36 .
      - run:
          name: isort Import Ordering Check  # Only validation, without re-formatting
          command: |
            isort --check-only --profile black .
      - run:
          name: Flake8 Lint Check  # Uses setup.cfg for configuration
          command: |
            flake8 . --count --statistics
      - run:
          name: Pylint Lint Check # Uses .pylintrc for configuration
          command: |
            pylint scaleapi
      - run:
          name: Build Package # create whl and install package
          command: |
            set -e
            python setup.py sdist bdist_wheel
            pip install --no-cache-dir dist/*.whl
      - run:
          name: Pytest Test Cases
          command: |  # Run test suite, uses SCALE_TEST_API_KEY env variable
            pytest -v
      - run:
          name: Twine PyPI Check
          command: |  # Validate distribution and setup.py configuration
            twine check --strict dist/*
  pypi_publish:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Validate Tag Version  # Check if the tag name matches the package version
          command: |
            PKG_VERSION=$(sed -n 's/^__version__ = //p' scaleapi/_version.py | sed -e 's/^"//' -e 's/"$//')

            if [[ "$CIRCLE_TAG" != "v${PKG_VERSION}" ]]; then
                echo "ERROR: Tag name ($CIRCLE_TAG) must match package version (v${PKG_VERSION})."
                exit 1;
            fi
      - run:
          name: Validate SDK Version Increment  # Check if the version is already on PyPI
          command: |
            PKG_VERSION=$(sed -n 's/^__version__ = //p' scaleapi/_version.py | sed -e 's/^"//' -e 's/"$//')

            if pip install "scaleapi>=${PKG_VERSION}" > /dev/null 2>&1;
            then
                echo "ERROR: You need to increment to a new version before publishing!"
                echo "Version (${PKG_VERSION}) already exists on PyPI."
                exit 1;
            fi
      - run:
          name: Install Environment Dependencies
          command: |  # install env dependencies
            set -e
            pip install --upgrade pip
            pip install twine
      - run:
          name: Build and Validate
          command: |  # create whl, validate with twine
            set -e
            python setup.py sdist bdist_wheel
            twine check --strict dist/*
      - run:
          name: Publish to PyPI
          command: |
            if test -z "${TWINE_USERNAME}" || test -z "${TWINE_PASSWORD}" ; then
                echo "ERROR: Please assign TWINE_USERNAME and TWINE_PASSWORD as environment variables"
                exit 1
            fi
            twine upload dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - pypi_publish:
          requires:
            - build_test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/  # Runs only for tags with the format [v1.2.3]
            branches:
              ignore: /.*/  # Runs for none of the branches
