# coding: utf-8

# flake8: noqa
"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from scaleapi.api_client.v2.models.annotation import Annotation
from scaleapi.api_client.v2.models.annotation_category import AnnotationCategory
from scaleapi.api_client.v2.models.annotation_category_multiple import AnnotationCategoryMultiple
from scaleapi.api_client.v2.models.annotation_category_multiple_properties import AnnotationCategoryMultipleProperties
from scaleapi.api_client.v2.models.annotation_category_properties import AnnotationCategoryProperties
from scaleapi.api_client.v2.models.annotation_integer import AnnotationInteger
from scaleapi.api_client.v2.models.annotation_integer_properties import AnnotationIntegerProperties
from scaleapi.api_client.v2.models.annotation_metadata import AnnotationMetadata
from scaleapi.api_client.v2.models.annotation_text import AnnotationText
from scaleapi.api_client.v2.models.annotation_text_properties import AnnotationTextProperties
from scaleapi.api_client.v2.models.annotation_type import AnnotationType
from scaleapi.api_client.v2.models.audio_file import AudioFile
from scaleapi.api_client.v2.models.base_annotation import BaseAnnotation
from scaleapi.api_client.v2.models.batch import Batch
from scaleapi.api_client.v2.models.delivery import Delivery
from scaleapi.api_client.v2.models.detailed_file import DetailedFile
from scaleapi.api_client.v2.models.error_detail import ErrorDetail
from scaleapi.api_client.v2.models.error_type import ErrorType
from scaleapi.api_client.v2.models.expandable import Expandable
from scaleapi.api_client.v2.models.expandable_annotation import ExpandableAnnotation
from scaleapi.api_client.v2.models.expandable_batch import ExpandableBatch
from scaleapi.api_client.v2.models.expandable_delivery import ExpandableDelivery
from scaleapi.api_client.v2.models.expandable_enum_deliveries import ExpandableEnumDeliveries
from scaleapi.api_client.v2.models.expandable_enum_delivery import ExpandableEnumDelivery
from scaleapi.api_client.v2.models.expandable_enum_task import ExpandableEnumTask
from scaleapi.api_client.v2.models.expandable_project import ExpandableProject
from scaleapi.api_client.v2.models.file import File
from scaleapi.api_client.v2.models.get_delivered_tasks_response import GetDeliveredTasksResponse
from scaleapi.api_client.v2.models.get_deliveries_response import GetDeliveriesResponse
from scaleapi.api_client.v2.models.get_task500_response import GetTask500Response
from scaleapi.api_client.v2.models.get_tasks_response import GetTasksResponse
from scaleapi.api_client.v2.models.image_file import ImageFile
from scaleapi.api_client.v2.models.message import Message
from scaleapi.api_client.v2.models.message_content import MessageContent
from scaleapi.api_client.v2.models.message_role import MessageRole
from scaleapi.api_client.v2.models.model_parameters import ModelParameters
from scaleapi.api_client.v2.models.option import Option
from scaleapi.api_client.v2.models.project import Project
from scaleapi.api_client.v2.models.reference_text import ReferenceText
from scaleapi.api_client.v2.models.submission import Submission
from scaleapi.api_client.v2.models.task import Task
from scaleapi.api_client.v2.models.task_status import TaskStatus
from scaleapi.api_client.v2.models.thread import Thread
from scaleapi.api_client.v2.models.turn import Turn
from scaleapi.api_client.v2.models.v1_task_task_id_get200_response import V1TaskTaskIdGet200Response
from scaleapi.api_client.v2.models.v1_task_task_id_get200_response_response import V1TaskTaskIdGet200ResponseResponse
