# coding: utf-8

"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from scaleapi.api_client.v2.models.batch_status import BatchStatus
from scaleapi.api_client.v2.models.expandable_project import ExpandableProject
from typing import Optional, Set
from typing_extensions import Self

class Batch(BaseModel):
    """
    Batch
    """ # noqa: E501
    id: StrictStr = Field(description="A unique identifier for the batch.")
    name: StrictStr = Field(description="The name of the batch.")
    project: ExpandableProject = Field(description="Project ID or [Project](/core-resources/project) associated with the batch.")
    created_at: datetime = Field(description="A timestamp formatted as an ISO 8601 date-time string.")
    completed_at: Optional[datetime] = Field(default=None, description="A timestamp formatted as an ISO 8601 date-time string.")
    status: BatchStatus
    callback: Optional[StrictStr] = Field(default=None, description="Callback URL or email for the batch.")
    metadata: Dict[str, Any] = Field(description="Metadata for the batch.")
    __properties: ClassVar[List[str]] = ["id", "name", "project", "created_at", "completed_at", "status", "callback", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        excluded_fields: Set[str] = set([
        ])
        return self.model_dump_json(by_alias=True, exclude_unset=True, exclude=excluded_fields)

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Batch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Batch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "project": ExpandableProject.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "created_at": obj.get("created_at"),
            "completed_at": obj.get("completed_at"),
            "status": obj.get("status"),
            "callback": obj.get("callback"),
            "metadata": obj.get("metadata")
        })
        return _obj


