# coding: utf-8

"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorType(str, Enum):
    """
    Type of the error
    """

    """
    allowed enum values
    """
    UNSUPPORTED_LANGUAGE = 'UNSUPPORTED_LANGUAGE'
    LANGUAGE_MISMATCH = 'LANGUAGE_MISMATCH'
    PROMPT_LENGTH_EXCEEDED = 'PROMPT_LENGTH_EXCEEDED'
    INVALID_CATEGORY = 'INVALID_CATEGORY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorType from a JSON string"""
        return cls(json.loads(json_str))
