# coding: utf-8

"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GenAIProjectType(str, Enum):
    """
    GenAIProjectType
    """

    """
    allowed enum values
    """
    SFT = 'SFT'
    RLHF_COLON__PREF_RANKING = 'RLHF: Pref Ranking'
    RLHF_COLON__PREF_RANKING_WITH_REWRITES = 'RLHF: Pref Ranking with Rewrites'
    RLVR_COLON__REINFORCEMENT_LEARNING_WITH_VERIFIABLE_REWARDS = 'RLVR: Reinforcement Learning with Verifiable Rewards'
    RUBRICS = 'Rubrics'
    PROCESS_SUPERVISION = 'Process Supervision'
    EVALS = 'Evals'
    PROMPT_GENERATION = 'Prompt Generation'
    CONTENT_UNDERSTANDING = 'Content Understanding'
    OTHER = 'Other'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GenAIProjectType from a JSON string"""
        return cls(json.loads(json_str))
