# coding: utf-8

"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Option(str, Enum):
    """
    Property that can be included in the annotations
    """

    """
    allowed enum values
    """
    ANNOTATION_DETAILS = 'annotation_details'
    ATTACHMENT_DETAILS = 'attachment_details'
    MODEL_PARAMETERS = 'model_parameters'
    SUBMISSIONS = 'submissions'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Option from a JSON string"""
        return cls(json.loads(json_str))
