# coding: utf-8

"""
    GenAI API Spec

    Data Engine: Generative AI API Specification

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TaskStatus(str, Enum):
    """
    The current status of the task, indicating whether it is pending, completed, error, or canceled.
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    COMPLETED = 'completed'
    CANCELED = 'canceled'
    ERROR = 'error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TaskStatus from a JSON string"""
        return cls(json.loads(json_str))
